--DECLARE @MyDatetime datetime = '2013-01-07';

CREATE VIEW BASIC_VIEW AS 
WITH CUSTOMER_WITH_BEST_CREDITS(CUSTOMER_NAME, CREDIT_LIMIT, ORDER_DATE ) AS (
SELECT TOP 10 SALES.CUSTOMERS.CUSTOMERNAME, 
RANK() OVER (ORDER BY SALES.CUSTOMERS.CreditLimit),
SALES.ORDERS.OrderDate 
FROM SALES.CUSTOMERS LEFT JOIN SALES.Orders ON SALES.ORDERS.CustomerID = SALES.Customers.CustomerID 
WHERE YEAR(SALES.ORDERS.ORDERDATE) = 2013 ORDER BY SALES.ORDERS.Comments, SALES.ORDERS.OrderDate, 
SALES.CUSTOMERS.CUSTOMERNAME)  

SELECT * FROM CUSTOMER_WITH_BEST_CREDITS;	